const accessControl = {
  admin: [
    '/ventas/panel',
    '/ventas',
    '/clientes',
    '/compras',
    '/compras/facturas',
    '/proveedores',
    '/tiendas',
    '/usuarios',
    '/formas-pago',
    '/dispositivos',
    '/lineas',
    '/departamentos',
    '/categorias',
    '/monedas',
    '/impuestos',
    '/cajas',
    '/inventarioConsulta',
    '/reportes',
    '/utilidad',
    '/kardex',
    '/pagos-cliente',
    '/backup',
    '/restore',
    '/schedule',
  ],
  facturacion: [
    '/ventas',
    '/clientes',
    '/inventarioConsulta',
    '/compras',
    '/compras/facturas',
    '/proveedores',
    '/ventas/panel',
    '/pagos-cliente',
  ],
  contabilidad: [
    '/formas-pago',
    '/monedas',
    '/inventarioConsulta',
    '/impuestos',
    '/reportes',
    '/utilidad',
    '/kardex'
  ],
  ventas: [
    '/ventas/panel',
    '/ventas',
    '/clientes', 
    '/categorias',
    '/inventarioConsulta',   
    '/pagos-cliente',
  ],
};
export default accessControl;
